---
name: 'CI/CD pipeline'

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: softorca/dummy-backed:${{ github.sha }}

      - name: Push to dokku (master)
        if: github.ref == 'refs/heads/main'
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@git.rollinggates.work:22/dummy-master'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: softorca/dummy-backed:${{ github.sha }}

      - name: Push to dokku (dev)
        if: github.ref == 'refs/heads/develop'
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@git.rollinggates.work:22/dummy'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: softorca/dummy-backed:${{ github.sha }}
