name: Deploy To Digital Ocean

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            docker system prune --force
            cd dev/dummy-backed
            git checkout develop
            git pull
            echo "${{ vars.ENVIROMENT_VARIABLES }}" > .env
            docker-compose down
            docker-compose up --build -d
            exit