name: Deploy To Digital Ocean

on:
  push:
    branches: [develop]

jobs:
  api-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build -t dummy-server:${{ github.sha }} .

      - name: Save docker image as tar
        run: |
          docker save dummy-server:${{ github.sha }} -o dummy-server.tar
          chmod 644 dummy-server.tar

      - name: Copy docker image to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          source: dummy-server.tar
          target: ~/images

      - name: Load docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            docker load -i /root/images/dummy-server.tar
            docker rm -f dummy-server
            docker run -dp 4000:4000 --name dummy-server dummy-server:${{ github.sha }}
