name: Greeting on variable day

on:
  push:
    branches: [develop]

env:
  DAY_OF_WEEK: Monday
  ITEM: ${{ vars.ITEM }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! no more $ITEM."
        env:
          First_Name: Mona